import type { Metadata } from 'next'
import { fetchAsteroid, getFormattedDate } from '@/utils'
import css from './index.module.scss'

interface IParams {
  params: {
    id: string
  }
}

export const metadata: Metadata = {
  title: 'Asteroid',
  description: 'Generated by create next app',
}

const AsteroidPage = async ({ params: { id } }: IParams) => {
  const asteroid = await fetchAsteroid(id)

  return (
    <section className={css.container} >
      <h2 className={css.title}>Астероид: {asteroid.name}</h2>
      {
        asteroid.close_approach_data.map(data => {
          return (
            <div key={data.close_approach_date_full} className={css.approach}>
              <p>{getFormattedDate(data.close_approach_date)}</p>
              <p>Скорость относительно Земли: {parseInt(data.relative_velocity.kilometers_per_second)} км/с</p>
              <p>Время максимального сближения: {data.close_approach_date_full.slice(-5)}</p>
              <p>Расстояние до Земли: {parseInt(data.miss_distance.kilometers)} км</p>
              <p>Вращается вокруг: {data.orbiting_body}</p>
            </div>
          )
        })
      }
    </section>
  )
}

export default AsteroidPage