import type { Metadata } from 'next'
import { fetchAsteroids } from '@/utils'
import AsteroidList from '@/components/asteroidList'

export const metadata: Metadata = {
  title: 'Asteroid API',
  description: 'Generated by create next app',
}

export default async function Home() {
  const data = await fetchAsteroids()

  return <AsteroidList data={data} />

}
